package exercicios;

/**
 * inglês: "Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms."
 * <p>
 * português: "Cada novo termo na sequência de Fibonacci é gerado pela adição dos dois termos anteriores.
 * Começando com 1 e 2, os primeiros 10 termos serão:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
 * <p>
 * Considerando os termos da sequência de Fibonacci cujos valores não excedem quatro milhões,
 * encontre a soma dos termos de valor par."
 *
 */
public class Ex02 {
	public static void main(String[] args) {
		int num1 = 1, num2 = 2, cache = num2, result = 0;
		
		while (num2 < 4_000_000){
			if (num2 % 2 == 0){
				result += num2;
			}
			num2 += num1;
			num1 = cache;
			cache = num2;
		}
		
		System.out.println(result);
		
	}
}
